---
- hosts: localhost

  tasks:
    - name: Print to the screen
      debug:
        msg: "This is your secret playbook. You and you alone must retain control of it. Your mission, Jim, should you choose to accept it. Is to first encrypt, then run this playbook (while it is encrypted). This message will self-destruct in 5 seconds."

